network:
    version: 2
    renderer: networkd
    ethernets:
        enp1s0:
            dhcp4: yes
        enp2s0:
            dhcp4: yes
        enp3s0:
            dhcp4: yes
        enp4s0:
            dhcp4: yes
        enp5s0:
            dhcp4: yes
        enp6s0:
            dhcp4: yes